### ISSUE TITLE
README: $zip.add instead of $obj.add?

### ISSUE THREAD

**Issue by tbrowder** [pmqs/Archive-SimpleZip#5]
If I read the code correctly, that $zip call is supposed to work, but it doesn't for me, nor does the glob. However, it does the job I need very well! Thanks.

**Comment by pmqs** [comment]
Hey Tom

just to clarify -- is the issue just the typo (use of `$zip`, where it should be `$obj`), or are you having ussie with advertised functionality?

**Comment by pmqs** [comment]
No updates in 6 months, so closing.
